export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_COUNT = 'UPDATE_COUNT'; 
export const UPDATE_TABSHOW = 'UPDATE_TABSHOW'; 
export const ADD_CARTGOODS = 'ADD_CARTGOODS'; 
export const INIT_CART = 'INIT_CART';
export const DELETE_CARTGOODS = 'DELETE_CARTGOODS';
export const UPDATE_CARTGOODS = 'UPDATE_CARTGOODS';
export const ALLSELECT_CARTGOODS = 'ALLSELECT_CARTGOODS';
export const ADD_EVALUATE = 'ADD_EVALUATE';

